mybatis:
  config-location: classpath:mybatis/SqlMapConfig.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.10.101:3306/e3mall
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    solr:
      host: http://127.0.0.1:8983/solr/collection1
#      repositories:
#        enabled: true
#      zk-host: 127.0.0.1:2182,127.0.0.1:2183,127.0.0.1:2184
  activemq:
    user: admin
    password: admin
    broker-url: tcp://127.0.0.1:61616
    pool:
      enabled: true
      max-connections: 50
    packages:
      trust-all: false

dubbo:
  application:
    name: e3-search
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    basePackages: guo.ping.e3mall.search.service
  protocol:
    port: 20882