server.port=8023
server.tomcat.uri-encoding=UTF-8
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
dubbo.application.name=item-web
dubbo.registry.address=zookeeper://39.104.87.118:2181 
dubbo.registry.protocol=zookeepe
app.name=订单详情页
app.version=1.0
HTML_GEN_PATH=~/HTML

